name: Mi Primer Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  saludar:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - run: echo "Â¡Hola Mundo!"
      
      - name: Generar archivo de log
        run: |
          echo "Build ejecutado en: $(date)" > build.log
          echo "Sistema operativo: ${{ matrix.os }}" >> build.log
        shell: bash

      - name: Subir artifact del log
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}
          path: build.log
      
      - name: Simular deploy (solo en main)
        if: github.ref == 'refs/heads/main'
        run: echo "ðŸš€ Realizando deploy automÃ¡tico desde la rama main..."
